name: neural-graph
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.4
  - numpy=1.21.6
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.9.0
  - networkx=2.6.3
  - matplotlib
  - cudatoolkit=10.1
  - pip
  - pip:
    - deepsnap==0.1.2
    - test_tube==0.7.5
    - tqdm==4.43.0
    - shapely
